name: Release
run-name: Release
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  repository_dispatch:
    types:
      - Global_Fetch
  workflow_dispatch:   
  schedule:
    - cron: '0 0/6 * * *'
  push:
    paths:
      - 'registry/**'
      - 'index.**'
concurrency:
  group: release-main
  cancel-in-progress: true
permissions:
  id-token: write
  contents: write
  attestations: write
jobs:
  fetch-pki:
    name: Fetch PKI
    concurrency:
      group: release
    uses: 0mniteck/.pki/.github/workflows/fetch.yml@c83fee7684f9f08a5e285d828d003503e7941a28 # v0.0.174
  release-pki:
    name: Release PKI
    concurrency:
      group: release
    needs: fetch-pki
    uses: 0mniteck/.pki/.github/workflows/immutable.yml@07c9eaf3eaa6e231105b1a07d9add847e07db353 # v0.0.100
  attested-rel:
    name: Attest PKI
    runs-on: ubuntu-latest
    environment:
      name: release
    needs: release-pki
    permissions:
      id-token: write
      contents: read
      attestations: read
    concurrency:
      group: release
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ssh-strict: true
          ssh-user: git
          clean: true
          show-progress: true
          persist-credentials: true
      - name: Run gh attestation verify
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for I in $GITHUB_WORKSPACE/.github/workflows/* $GITHUB_WORKSPACE/registry/* $GITHUB_WORKSPACE/index.* $GITHUB_WORKSPACE/local.sh ; do
            gh attestation verify $I --repo 0mniteck/.pki --source-ref refs/heads/main \
            --signer-workflow 0mniteck/.pki/.github/workflows/immutable.yml || exit 1;
            sleep 1 && echo "$I Attested"
          done;
          echo DONE
  read-me:
    name: Publish Readme
    uses: 0mniteck/.pki/.github/workflows/read-me.yml@29fd7ce1b8f060a415f076df972306e64f5078a0 # v0.0.27
    concurrency:
      group: release
    needs:
      - attested-rel
      - release-pki
    permissions:
      id-token: write
      contents: write
    with:
      attested_url: "${{ needs.release-pki.outputs.URL }}"
  gh-pages:
    name: Release Github Pages
    uses: 0mniteck/.pki/.github/workflows/gh-pages.yml@ef7b94205b6f88fe77ed3074e2fb5073b76f804b # v0.0.100
    concurrency:
      group: release
    needs: read-me
    permissions:
      contents: read
      pages: write
      id-token: write
