name: Check Attestation
run-name: Check Attestation
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  workflow_dispatch:   
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'registry/**'
      - 'index.**'
concurrency:
  group: attestation-main
  cancel-in-progress: true
permissions:
  id-token: write
  contents: write
  attestations: write
jobs:
  release-pki:
    name: Release PKI
    concurrency:
      group: attestation
    uses: 0mniteck/.pki/.github/workflows/immutable.yml@c799ee8634a3b7ca0376912a08b2313045ab4f6d # v0.0.18
  immutable-rel:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pki.omniteck.com
    needs: release-pki
    permissions:
      id-token: write
      contents: read
      attestations: read
    concurrency:
      group: attestation
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ssh-strict: true
          ssh-user: git
          clean: true
          show-progress: true
          persist-credentials: true
      - name: Run gh attestation verify - GitHub CLI 2.50+
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for I in $GITHUB_WORKSPACE/.github/workflows/* $GITHUB_WORKSPACE/registry/* $GITHUB_WORKSPACE/index.* $GITHUB_WORKSPACE/local.sh ; do
            gh attestation verify $I --repo 0mniteck/.pki --source-ref refs/heads/main \
            --signer-workflow 0mniteck/.pki/.github/workflows/immutable.yml || exit 1;
            sleep 1 && echo "$I Attested"
          done;
          echo DONE
  read-me:
    name: Update Readme
    uses: 0mniteck/.pki/.github/workflows/readme.yml@31c599591db3f3a10ff6ee7a51a61deccfa33ff1 # v0.0.18
    concurrency:
      group: attestation
    needs: release-pki
    permissions:
      id-token: write
      contents: write
    with:
      attested_url: "${{ needs.release-pki.outputs.URL }}"
  gh-pages:
    name: Refresh Github Pages
    uses: 0mniteck/.pki/.github/workflows/gh-pages.yml@13a2c53b7477903cc3ccbddf478646d3d50899ca # v0.0.18
    concurrency:
      group: attestation
    needs: read-me
    permissions:
      contents: read
      pages: write
      id-token: write
