name: Check Attestation
run-name: Check Attestation
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  workflow_dispatch:   
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'registry/**'
      - 'index.**'
concurrency:
  group: attestation
  cancel-in-progress: true
permissions:
  id-token: write
  contents: write
  attestations: write
jobs:
  release-pki:
    name: Release PKI
    uses: 0mniteck/.pki/.github/workflows/immutable.yml@a5399a0a0bbd2fd33ac81e1e16734820b3c7c4e8 # v0.0.18
  immutable-rel:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pki.omniteck.com
    needs: release-pki
    permissions:
      id-token: write
      contents: read
      attestations: read
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ssh-strict: true
          ssh-user: git
          clean: true
          show-progress: true
          persist-credentials: true
      - name: Run gh attestation verify - GitHub CLI 2.50+
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for I in $GITHUB_WORKSPACE/.github/workflows/* $GITHUB_WORKSPACE/registry/* $GITHUB_WORKSPACE/index.* $GITHUB_WORKSPACE/local.sh ; do
            gh attestation verify $I --repo 0mniteck/.pki --source-ref refs/heads/main \
            --signer-workflow 0mniteck/.pki/.github/workflows/immutable.yml || exit 1;
            sleep 1 && echo "$I Attested"
          done;
          echo DONE
  read-me:
    name: Update Readme
    uses: 0mniteck/.pki/.github/workflows/readme.yml@480afa813c40f94539671a37a7f6d31aca2ae221 # v0.0.18
    needs: release-pki
    with:
      attested_url: "${{ needs.release-pki.outputs.URL }}"
