name: Deploy GH-Pages
run-name: Deploy GH-Pages
on:
  workflow_call:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  release-page:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ssh-strict: true
          ssh-user: git
          clean: true
          show-progress: true
          persist-credentials: true
      - name: Git Pull
        run: |
          pushd $GITHUB_WORKSPACE > /dev/null
            git fetch && git pull origin main
          popd > /dev/null
      - name: Setup Github Pages v5
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
      - name: Build with Jekyll v1.0.13
        uses: actions/jekyll-build-pages@44a6e6beabd48582f863aeeb6cb2151cc1716697 # v1.0.13
        with:
          source: ./
          destination: ./_site
      - name: Upload Pages Artifact v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
  push-page:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: ${{ steps.deployment.outputs.page_url }}
    needs: release-page
    steps:
      - name: Deploy to GitHub Pages v4.0.5
        id: deployment
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
