name: Immutable Release
run-name: Immutable Release
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  workflow_call:
concurrency:
  group: immutable
  cancel-in-progress: true
jobs:
  fetch-pki:
    uses: 0mniteck/.pki/.github/workflows/fetch.yml@98015afa8c407b517e3522d5ece89a45f862361b #v0.0.12
  immutable-rel:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pki.omniteck.com
    needs: fetch-pki
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ssh-strict: true
          ssh-user: git
          clean: true
          show-progress: true
          persist-credentials: true
      - name: Generate Attestation for Build Provenance v3
        id: generate_attestation
        uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f # v3
        with:
            subject-path: |
              .github/workflows/**
              registry/**
              index.**
              local.sh
      - name: Fetch Attestation ID via API
        id: fetch_attestation
        run: |
          mkdir -p attestations && pushd attestations > /dev/null
          echo 1. ${{ steps.generate_attestation.outputs.bundle-path }} > Runner\ output\ \(log\)
          echo 2. ${{ steps.generate_attestation.outputs.attestation-url }} >> Runner\ output\ \(log\)
          cat Runner\ output\ \(log\) && popd > /dev/null
      - name: Download Attestation (json) via API
        id: download_attestation
        run: |
          pushd attestations > /dev/null
          curl -L -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          ${{ steps.generate_attestation.outputs.attestation-url }}/download > Build\ attestation\ \(json\)
          popd > /dev/null && echo "ver=$(cat index.ver)" >> $GITHUB_ENV
      - name: Draft Release via API
        id: draft_release
        run: |
          export -- response=$(curl -L -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/0mniteck/.pki/releases \
          -d '{
          "tag_name":"v0.0.${{ env.ver }}",
          "target_commitish":"main",
          "name":"v0.0.${{ env.ver }}",
          "body":"# DRAFT - Automated release workflow - DRAFT",
          "draft":true,
          "immutable":false,
          "prerelease":false,
          "generate_release_notes":false,
          "make_latest":"false" 
          }' | jq .id || exit 1) || exit 1
          echo "responded=$response" >> $GITHUB_ENV
      - name: Install GitReleaseManager - v4.3.3 - v0.20.0
        uses: gittools/actions/gitreleasemanager/setup@d96456f5d2fd78923086859f5328008482688611 # v4.3.3
        with:
          versionSpec: "0.20.0"
      - name: Add assets to draft release
        uses: gittools/actions/gitreleasemanager/addasset@ee6b1e33085776d48cb0d657e9161ba6d367bc69 # v4.3.3
        with:
          token: "${{ github.token }}"
          repository: "0mniteck/.pki"
          milestone: "v0.0.${{ env.ver }}"
          assets: |
            attestations/**
      - name: Publish Release via API
        run: |
          result=$(curl -L -X PATCH -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/0mniteck/.pki/releases/${{ env.responded }} \
          -d '{
          "tag_name":"v0.0.${{ env.ver }}",
          "target_commitish":"main",
          "name":"v0.0.${{ env.ver }}",
          "body":"## Attestable - Immutable - Ephemeral
          > #### Attestation Created - v0.0.${{ env.ver }} Immutable Tag
          > <a href=${{ steps.generate_attestation.outputs.attestation-url }} >${{ steps.generate_attestation.outputs.attestation-url }}</a>
          ## ",
          "draft":false,
          "immutable":true,
          "prerelease":false,
          "generate_release_notes":true,
          "make_latest":"true"
          }') || exit 1
          if [[ "$result" == "null" ]]; then exit 1; fi;
