name: Add Release Tag To README
run-name: Add Release Tag To README
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  workflow_call:
    inputs:
      attested_id: 
        required: true
        description: 'id number of attestation'
        type: string
concurrency:
  group: rel-tag
  cancel-in-progress: true
jobs:
  release-tag:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pki.omniteck.com
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ssh-strict: true
          ssh-user: git
          clean: true
          show-progress: true
          persist-credentials: true
      - name: Update Readme
        run: |
          pushd $GITHUB_WORKSPACE > /dev/null
            echo "GITHUB_REF is $GITHUB_REF" >> $GITHUB_STEP_SUMMARY
            VER=$(($(cat index.ver) - 1 ))
            echo $VER
            sed -i "s/$(echo $(grep Created README.md))/> #### Attestation Created - v0.0.$VER Immutable Tag/" README.md
            INP="> - [https://github.com/0mniteck/.pki/attestations/${{ inputs.attested_id }}](https://github.com/0mniteck/.pki/attestations/${{ inputs.attested_id }})"
            sed -i "$(( $(grep -n Created README.md | cut -d':' -f1) + 1))d" README.md
            sed -i "$(( $(grep -n Created README.md | cut -d':' -f1) + 1))i $INP" README.md
            sed -i "s/$(echo $(grep Created README.md))/> #### Attestation Created - v0.0.$(cat index.ver) Immutable Tag/" README.md
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add -A && git commit -m "v0.0.$VER - $(date '+on %m/%d/%y at %H:%M UTC')"
            git push origin HEAD:main
          popd > /dev/null && echo DONE
