name: Publish README.md
run-name: Publish README.md
on:
  workflow_call:
    inputs:
      attested_url: 
        required: true
        description: 'url of attestation'
        type: string
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  publish-readme:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ssh-strict: true
          ssh-user: git
          clean: true
          show-progress: true
          persist-credentials: true
      - name: Update Readme
        run: |
          pushd $GITHUB_WORKSPACE > /dev/null
            git fetch && git pull origin main
            VER=$(($(cat index.ver) - 1 ))
            sed -i "s/$(echo $(grep Created README.md))/> #### Attestation Created - v0.0.$VER Immutable Tag/" README.md
            INP="> - [${{ inputs.attested_url }}](${{ inputs.attested_url }})"
            sed -i "$(( $(grep -n Created README.md | cut -d':' -f1) + 1))d" README.md
            sed -i "$(( $(grep -n Created README.md | cut -d':' -f1) + 1))i $INP" README.md
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add -A && git commit -m "Released v0.0.$VER - $(date '+on %m/%d/%y at %H:%M UTC')"
            git push origin HEAD:main
          popd > /dev/null && echo DONE
