name: Release
run-name: Release
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  repository_dispatch:
    types:
      - Global_Fetch
  workflow_dispatch:   
  schedule:
    - cron: '0 0/6 * * *'
  push:
    paths:
      - 'registry/**'
      - 'index.**'
concurrency:
  group: release-main
  cancel-in-progress: true
permissions:
  id-token: write
  contents: write
  attestations: write
  artifact-metadata: write
jobs:
  fetch-pki:
    name: Fetch PKI
    concurrency:
      group: release
    uses: 0mniteck/.pki/.github/workflows/fetch.yml@cd839797193a83820be78dbcfa9c73d1909308c6 # v0.0.179
  release-pki:
    name: Release PKI
    concurrency:
      group: release
    needs: fetch-pki
    uses: 0mniteck/.pki/.github/workflows/immutable.yml@6c4f06c54cdc4a338efbf28c78977b6357a46f23 # v0.0.181
  attested-rel:
    name: Attest PKI
    runs-on: ubuntu-latest
    environment:
      name: release
    needs: release-pki
    permissions:
      id-token: write
      contents: read
      attestations: read
    concurrency:
      group: release
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Git fetch
        id: git_fetch
        run: git fetch && git pull origin main && echo Fetched
      - name: Run gh attestation verify
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          for I in ${{github.workspace}}/.github/{actions/Jekyll,workflows}/* ${{github.workspace}}/registry/* ${{github.workspace}}/index.* ${{github.workspace}}/local.sh ; do
            gh attestation verify $I --repo 0mniteck/.pki --source-ref refs/heads/main \
            --signer-workflow 0mniteck/.pki/.github/workflows/immutable.yml --digest-alg sha512 || exit 1;
            echo "$I Attested"; done; echo DONE;
  read-me:
    name: Publish Readme
    uses: 0mniteck/.pki/.github/workflows/read-me.yml@c74b68c8e463e7881e6d10660fdc5092a62582d6 # v0.0.175
    concurrency:
      group: release
    needs:
      - attested-rel
      - release-pki
    permissions:
      id-token: write
      contents: write
    with:
      attested_url: "${{needs.release-pki.outputs.URL}}"
  gh-pages:
    name: Release Github Pages
    uses: 0mniteck/.pki/.github/workflows/gh-pages.yml@0cf603adf6fba71a9d9fc649cbc08c9751a15e00 # v0.0.185
    concurrency:
      group: release
    needs: read-me
    permissions:
      contents: read
      pages: write
      id-token: write
