name: Release
run-name: Release
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  repository_dispatch:
    types:
      - Global_Fetch
  workflow_dispatch:
  schedule:
    - cron: '0 0/6 * * *'
  push:
    paths:
      - 'registry/**'
      - 'index.**'
permissions: {}
concurrency:
  group: release-main
  cancel-in-progress: true
jobs:
  fetch-pki:
    name: Fetch PKI
    permissions:
      id-token: write
      contents: write
    concurrency:
      group: release
    secrets:
      DOCKER: ${{secrets.DOCKER}}
    uses: 0mniteck/.pki/.github/workflows/fetch.yml@bb6d607e8977f7a21d2cc7b81804dc6becf88ed6 # v0.0.247
  release-pki:
    name: Release PKI
    concurrency:
      group: release
    needs: fetch-pki
    uses: 0mniteck/.pki/.github/workflows/immutable.yml@90bfc66bf5b3e1b38b998906d7dae4633abb0474 # v0.0.247
  attested-rel:
    name: Attest PKI
    environment:
      name: release
    needs: release-pki
    permissions:
      id-token: write
      contents: read
      attestations: read
    concurrency:
      group: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Git fetch
        run: git fetch && git pull origin main && echo Fetched
      - name: Run gh attestation verify
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          for I in ${{github.workspace}}/.github/{actions/jekyll,workflows}/* ${{github.workspace}}/registry/* ${{github.workspace}}/index.* ${{github.workspace}}/local.sh ; do
            gh attestation verify $I --repo 0mniteck/.pki --source-ref refs/heads/main \
            --signer-workflow 0mniteck/.pki/.github/workflows/immutable.yml --digest-alg sha512 || exit 1;
            echo "$I Attested"; done; echo DONE;
  read-me:
    name: Publish Readme
    uses: 0mniteck/.pki/.github/workflows/read-me.yml@d2748b9108892c35d35e2c203ed2e7b897e5d1e6 # v0.0.247
    concurrency:
      group: release
    needs:
      - attested-rel
      - release-pki
    with:
      attested_url: "${{needs.release-pki.outputs.URL}}"
  gh-pages:
    name: Release Github Pages
    permissions: 
      id-token: write
      pages: write
      contents: read
    concurrency:
      group: release
    needs: read-me
    uses: 0mniteck/.pki/.github/workflows/gh-pages.yml@d3d945da30fd098eae4b71990968a2a9c1623af1 # v0.0.247
