name: Release
run-name: Release
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  repository_dispatch:
    types:
      - Global_Fetch
  workflow_dispatch:   
  schedule:
    - cron: '0 0/6 * * *'
  push:
    paths:
      - 'registry/**'
      - 'index.**'
concurrency:
  group: release-main
  cancel-in-progress: true
permissions:
  id-token: write
  contents: write
  attestations: write
  artifact-metadata: write
jobs:
  fetch-pki:
    name: Fetch PKI
    concurrency:
      group: release
    uses: 0mniteck/.pki/.github/workflows/fetch.yml@f481239fca624eaa3b0825fbe756c571a9a535a4 # v0.0.175
  release-pki:
    name: Release PKI
    concurrency:
      group: release
    needs: fetch-pki
    uses: 0mniteck/.pki/.github/workflows/immutable.yml@23386e8d898a859f651b92972a3e647d977ebac2 # v0.0.175
  attested-rel:
    name: Attest PKI
    runs-on: ubuntu-latest
    environment:
      name: release
    needs: release-pki
    permissions:
      id-token: write
      contents: read
      attestations: read
    concurrency:
      group: release
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ssh-strict: true
          ssh-user: git
          clean: true
          show-progress: false
          persist-credentials: true
      - name: Run gh attestation verify
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for I in $GITHUB_WORKSPACE/.github/workflows/* $GITHUB_WORKSPACE/registry/* $GITHUB_WORKSPACE/index.* $GITHUB_WORKSPACE/local.sh ; do
            gh attestation verify $I --repo 0mniteck/.pki --source-ref refs/heads/main \
            --signer-workflow 0mniteck/.pki/.github/workflows/immutable.yml || exit 1;
            sleep 1 && echo "$I Attested"
          done;
          echo DONE
  read-me:
    name: Publish Readme
    uses: 0mniteck/.pki/.github/workflows/read-me.yml@c7a418ef0d4c7a71879cc6c7223251884145805f # v0.0.175
    concurrency:
      group: release
    needs:
      - attested-rel
      - release-pki
    permissions:
      id-token: write
      contents: write
    with:
      attested_url: "${{ needs.release-pki.outputs.URL }}"
  gh-pages:
    name: Release Github Pages
    uses: 0mniteck/.pki/.github/workflows/gh-pages.yml@7e0e7abc8652438ae63037545322baabe2c5f137 # v0.0.175
    concurrency:
      group: release
    needs: read-me
    permissions:
      contents: read
      pages: write
      id-token: write
